### ISSUE TITLE
loadGSC fails to read BiGG Model sbml file for GSA using reporter metabolites

### ISSUE THREAD

**Issue by janstrauss1** [varemo/piano#4]
Hi there,

I am trying to run a GSA using Reporter Metabolites using a genome-scale metabolic network reconstruction from the [BiGG Models database](http://bigg.ucsd.edu/).

Unfortunately, when I try to load the iML1515 _E. coli_ reconstruction using `loadGSC(file = "iML1515.xml", type = "sbml")`, I get: 
```
Error in loadGSC(file = "iML1515.xml", type = "sbml") : 
  no gene association found
```

I'm aware that 

> SBML loading is an experimental feature and is highly dependent on the version and format of the SBML file and requires it to contain gene associations for the reactions

but it surprises me that there seem to be no gene associates in the BiGG models sbml files. 

Is there any way to overcome this issue? Which sbml files/ databases are currently supported by piano?

Many thanks in advance!

**Comment by varemo** [comment]
Hi,

This feature is unfortunately a bit sketchy, and since the usage frequency is very low this is not something I have prioritized. 

My general recommendation is to "simply" parse out the information you need from the model, in this case the gene-metabolite association, and load it using loadGSC either from a plain text file or as an R data.frame object. The format should be two columns where each row gives one unique gene-metabolite association. 

I am not aware of how gene associations are annotated in BiGG models, but if it is there it should be possible to parse out. (The initial code and reason to include this feature was to match the format of gene associations used in the models developed by the research group I was in at the time.)

Sorry for not being more helpful but I hope that this information will lead you in the right direction.

**Comment by janstrauss1** [comment]
Hi @varemo,
thanks a lot for the directions!
I have successfully parsed out the gene-metabolite associations from the BiGG model using [framed](https://github.com/cdanielmachado/framed) with invaluable help from @cdanielmachado and successfully run a GSA using Reporter Metabolites.

**Comment by cdanielmachado** [comment]
👍

**Comment by OmarAshkar** [comment]
Hi @janstrauss1 and  @cdanielmachado, this issue is relevant to me and I started a duplicate #8  issue before I found this. Can you share a little tips and code to get me to solve that issue?

**Comment by janstrauss1** [comment]
Hi @OAshkar,

You can find code provided by @cdanielmachado to parse out the gene-metabolite associations at https://gist.github.com/cdanielmachado/826d8199b5e2019c4389d7295504f238.

Hope this helps!
